export enum Job {
    ACTOR = 'ACTOR',
    DIRECTOR = 'DIRECTOR',
    SCREENPLAY= 'SCREENPLAY',
    WRITER = 'WRITER',
    STORY = 'STORY',
    ORIGINAL_MUSIC_COMPOSER = 'ORIGINAL MUSIC COMPOSER',
    MUSIC_SUPERVISOR = 'MUSIC SUPERVISOR',
    PRODUCER = 'PRODUCER',
    DIRECTOR_OF_PHOTOGRAPHY = 'DIRECTOR OF PHOTOGRAPHY',

    CHARACTER_DESIGN = 'CHARACTER DESIGN',
    SERIES_DIRECTOR = 'SERIES DIRECTOR',
    LAYOUT_DESIGNER = 'LAYOUT DESIGNER',
    ART_DESIGNER = 'ART DESIGNER',
    COMIC_BOOK = 'COMIC BOOK',
    CREATURE_DESIGN = 'CREATURE DESIGN',
    THEME_SONG_PERFORMANCE = 'THEME SONG PERFORMANCE',
    KEY_ANIMATION = 'KEY ANIMATION',
    ANIMATION_DIRECTOR = 'ANIMATION DIRECTOR',
    ORIGINAL_STORY = 'ORIGINAL STORY',
    ANIMATION = 'ANIMATION',

    VISUAL_EFFECTS_TECHNICAL_DIRECTOR = 'VISUAL EFFECTS TECHNICAL DIRECTOR',
    SPECIAL_EFFECTS_SUPERVISOR = 'SPECIAL EFFECTS SUPERVISOR',
    VISUAL_EFFECTS_SUPERVISOR = 'VISUAL EFFECTS SUPERVISOR',
    VISUAL_EFFECTS = 'VISUAL EFFECTS'
}