export enum MediaType {
    MEDIA = "MEDIA",
    MOVIE = "MOVIE",
    SERIES = "SERIES",
    SEASON = "SEASON",
    EPISODE = "EPISODE",
    CREDIT = "CREDIT",
    SELECTION = "SELECTION",
    LICENSE = "LICENSE",
    CATEGORY = "CATEGORY",
    OTHER = "OTHER",
    ALL = "ALL",
    HISTORIC_USER = "HISTORIC_USER",
    LAST_RELEASE = "LAST_RELEASE"
}